"""Classification data ported verbatim from the retired Node scraper. Edit with tests."""
import re

BRANDS = ['ASUS ROG', 'ROG STRIX', 'ROG', 'ASUS TUF', 'ASUS', 'MSI', 'GIGABYTE AORUS', 'AORUS', 'GIGABYTE', 'ZOTAC',
 'CORSAIR', 'G.SKILL', 'GSKILL', 'G SKILL', 'KINGSTON FURY', 'KINGSTON', 'CRUCIAL', 'ADATA', 'XPG',
 'WESTERN DIGITAL', 'WD', 'SEAGATE', 'SAMSUNG', 'COOLER MASTER', 'COOLERMASTER', 'NZXT', 'LIAN LI', 'LIANLI',
 'DEEPCOOL', 'THERMALTAKE', 'ANT ESPORTS', 'ANTEC', 'AEROCOOL', 'GAMDIAS', 'NOCTUA', 'ARCTIC', 'BE QUIET',
 'PHANTEKS', 'LOGITECH', 'RAZER', 'HYPERX', 'STEELSERIES', 'LENOVO', 'HP', 'DELL', 'ACER', 'APPLE', 'TP-LINK',
 'TPLINK', 'BENQ', 'LG', 'AOC', 'VIEWSONIC', 'EVGA', 'PALIT', 'GALAX', 'INNO3D', 'SAPPHIRE', 'POWERCOLOR',
 'XFX', 'ASROCK', 'BIOSTAR', 'PNY', 'TEAMGROUP', 'TEAM GROUP', 'PATRIOT', 'WD BLACK', 'WD BLUE', 'KIOXIA',
 'SOLIDIGM', 'SK HYNIX', 'GAMESOUL', 'MICROMINI', 'TCOS TECH', 'UBISOFT', 'EA SPORTS', 'ACTIVISION',
 'ROCKSTAR GAMES', 'SQUARE ENIX', 'BANDAI NAMCO', 'CAPCOM', 'SEGA', 'KONAMI', 'NACON', 'SONY', 'MICROSOFT',
 'NINTENDO', 'NVIDIA', 'GEFORCE', 'AMD', 'RYZEN', 'INTEL', 'CORE']
BRAND_CANON = {'ROG': 'ASUS',
 'ROG STRIX': 'ASUS',
 'ASUS ROG': 'ASUS',
 'ASUS TUF': 'ASUS',
 'AORUS': 'GIGABYTE',
 'GIGABYTE AORUS': 'GIGABYTE',
 'KINGSTON FURY': 'Kingston',
 'GEFORCE': 'NVIDIA',
 'RYZEN': 'AMD',
 'CORE': 'Intel',
 'WD BLACK': 'WD',
 'WD BLUE': 'WD',
 'ASUS': 'ASUS',
 'MSI': 'MSI',
 'GIGABYTE': 'Gigabyte',
 'ZOTAC': 'ZOTAC',
 'NVIDIA': 'NVIDIA',
 'AMD': 'AMD',
 'INTEL': 'Intel',
 'KINGSTON': 'Kingston',
 'ADATA': 'ADATA',
 'XPG': 'XPG',
 'WD': 'WD',
 'NZXT': 'NZXT',
 'HP': 'HP',
 'LG': 'LG',
 'AOC': 'AOC',
 'EVGA': 'EVGA',
 'XFX': 'XFX',
 'PNY': 'PNY',
 'GALAX': 'GALAX',
 'INNO3D': 'INNO3D',
 'BENQ': 'BenQ',
 'ASROCK': 'ASRock',
 'HYPERX': 'HyperX',
 'STEELSERIES': 'SteelSeries',
 'VIEWSONIC': 'ViewSonic',
 'POWERCOLOR': 'PowerColor',
 'TP-LINK': 'TP-Link',
 'TPLINK': 'TP-Link',
 'GSKILL': 'G.Skill',
 'G SKILL': 'G.Skill',
 'G.SKILL': 'G.Skill',
 'COOLERMASTER': 'Cooler Master',
 'LIANLI': 'Lian Li',
 'DEEPCOOL': 'DeepCool',
 'TEAM GROUP': 'TeamGroup',
 'TEAMGROUP': 'TeamGroup',
 'SK HYNIX': 'SK Hynix',
 'GAMESOUL': 'GAMESOUL',
 'MICROMINI': 'MICROMINI',
 'TCOS TECH': 'TCOS TECH',
 'UBISOFT': 'Ubisoft',
 'EA SPORTS': 'EA Sports',
 'ACTIVISION': 'Activision',
 'ROCKSTAR GAMES': 'Rockstar Games',
 'SQUARE ENIX': 'Square Enix',
 'BANDAI NAMCO': 'Bandai Namco',
 'CAPCOM': 'Capcom',
 'SEGA': 'Sega',
 'KONAMI': 'Konami',
 'NACON': 'Nacon',
 'SONY': 'Sony',
 'MICROSOFT': 'Microsoft',
 'NINTENDO': 'Nintendo'}
TYPE_RULES = [('Motherboard',
  ['motherboard', 'mainboard', ' mobo', ' b550', ' b650', ' b660', ' b760', ' x570', ' x670', ' x870',
   ' z690', ' z790', ' z890', ' h510', ' h610', ' h770', ' a520', ' a620', 'b850', 'b860', 'b840', ' b450',
   ' b460', ' b560', ' h410', ' h310', ' z590', 'chipset']),
 ('Graphics Card',
  ['graphics card', 'graphic card', ' gpu', 'rtx ', 'gtx ', 'radeon', 'geforce', ' rx 6', ' rx 7', ' rx 9',
   'arc a3', 'arc a5', 'arc a7', 'video card']),
 ('Power Supply',
  ['power supply', ' psu', ' smps', 'watt psu', '80 plus', '80+', 'gold psu', 'bronze psu', 'modular psu']),
 ('Memory/RAM',
  [' ram ', 'ram kit', 'memory module', 'desktop memory', ' dimm', 'ddr3 ', 'ddr4 ', 'ddr5 ', 'sodimm']),
 ('SSD', [' ssd', 'nvme', ' m.2', 'm2 ssd', 'solid state', 'solid-state']),
 ('HDD', [' hdd', 'hard disk', 'hard drive', 'sata hdd', 'desktop drive']),
 ('PC Case/Chassis',
  ['cabinet', 'pc case', 'computer case', ' chassis', 'mid tower', 'full tower', 'mini tower',
   'gaming case']),
 ('Fans & Cooling',
  ['cpu cooler', 'air cooler', 'aio cooler', ' aio ', 'liquid cool', 'liquid cpu', 'heatsink', 'heat sink',
   'case fan', 'cooling fan', 'cpu fan', 'radiator']),
 ('Thermal Paste',
  ['thermal paste', 'thermal compound', 'thermal grease', 'thermal goop', ' mx-4', ' mx-7', 'kryonaut']),
 ('Monitor',
  ['monitor', 'inch led', 'ips panel', 'va panel', 'hz gaming', 'gaming display', 'curved display']),
 ('Mousepad', ['mouse pad', 'mousepad', 'mouse mat', 'deskmat', 'desk mat']),
 ('Keyboard', ['keyboard', 'mechanical kb']), ('Mouse', [' mouse', 'gaming mouse']),
 ('Gaming Accessories',
  ['gamepad', ' controller', 'joystick', 'dualsense', 'dualshock', 'xbox controller', 'capture card']),
 ('Webcam', ['webcam', 'web cam']), ('Microphone', ['microphone', 'condenser mic', 'usb mic', ' mic ']),
 ('Speakers', ['speaker', 'soundbar', 'sound bar', 'home theatre', 'home theater']),
 ('UPS', [' ups ', 'uninterruptible', 'power backup']),
 ('Networking',
  ['wifi adapter', 'wi-fi adapter', 'wireless adapter', 'network card', 'wifi card', 'lan card',
   'ethernet adapter', 'router']),
 ('Gaming Chair',
  ['gaming chair', 'ergonomic chair', 'office chair', 'computer chair', 'desk chair', 'mesh chair']),
 ('Pen Drive', ['pen drive', 'pendrive', 'flash drive', 'usb flash', 'usb drive']),
 ('Gaming Laptop', ['laptop', 'notebook']),
 ('Headset', ['headset', 'headphone', 'earphone', 'earbud', ' tws ', 'neckband']),
 ('Processor/CPU',
  ['processor', ' cpu', 'ryzen', 'core i3', 'core i5', 'core i7', 'core i9', 'threadripper', 'pentium',
   'celeron', 'core ultra'])]
PRICE_CAP = {'Graphics Card': 2500000,
 'Desktop PC': 2500000,
 'Gaming Laptop': 1500000,
 'Monitor': 1200000,
 'Processor/CPU': 900000,
 'Motherboard': 400000,
 'SSD': 400000,
 'Memory/RAM': 400000,
 'HDD': 300000,
 'PC Case/Chassis': 300000,
 'Power Supply': 200000,
 'Fans & Cooling': 200000,
 'Keyboard': 150000,
 'Mouse': 120000,
 'Mousepad': 50000,
 'Headset': 200000,
 'Webcam': 150000,
 'Microphone': 250000,
 'Speakers': 300000,
 'UPS': 500000,
 'Networking': 300000,
 'Gaming Chair': 300000,
 'Pen Drive': 100000,
 'Thermal Paste': 50000,
 'Gaming Accessories': 400000,
 'Accessories': 200000,
 'PlayStation': 150000,
 'Xbox': 150000,
 'Nintendo': 150000,
 'Games': 50000,
 'Components': 500000,
 'Other': 500000}
ACCESSORY_KW = ['sleeve', ' bag', 'backpack', 'pouch', 'holder', 'riser cable', 'riser kit', 'extension cable', 'cable comb',
 'cable management', 'cleaning kit', 'screwdriver', 'dust filter', 'dust plug', 'dust cover', 'port cover',
 'keycap', 'keyboard switch', 'switch set', 'switch puller', 'stabilizer', 'wrist rest', 'palm rest',
 'gpu support', 'vertical gpu', 'cooling pad', 'laptop table', 'pop filter', 'mic arm', 'boom arm',
 'card reader', 'usb hub', 'docking station', 'processor frame', 'contact frame', 'cpu frame', 'socket frame',
 'mounting frame', 'mounting kit', 'mounting bracket', 'mounting plate', 'backplate', 'stand-off',
 'standoff']
KEY_STOP = frozenset(['the', 'for', 'with', 'and', 'new', 'of', 'to', 'in', 'on', 'by', 'or', 'a', 'an', 'graphic', 'graphics',
 'card', 'gaming', 'game', 'desktop', 'laptop', 'processor', 'cpu', 'ram', 'memory', 'module', 'modules',
 'kit', 'ssd', 'nvme', 'hdd', 'drive', 'solid', 'state', 'internal', 'external', 'gen', 'pcie', 'pci',
 'interface', 'bit', 'channel', 'single', 'dual', 'dualchannel', 'edition', 'oc', 'rgb', 'argb', 'led',
 'cooler', 'fan', 'fans', 'motherboard', 'mainboard', 'power', 'supply', 'psu', 'smps', 'watt', 'watts',
 'inch', 'monitor', 'keyboard', 'mouse', 'wireless', 'wired', 'black', 'white', 'grey', 'gray', 'silver',
 'blue', 'red', 'series', 'ready', 'warranty', 'year', 'years', 'nvidia', 'amd', 'intel', 'geforce', 'radeon',
 'mhz', 'ghz', 'up', 'upto', 'cache', 'cores', 'thread', 'threads'])
KEY_VARIANT = ['ti', 'xt', 'xtx', 'gre', 'super', 'plus', 'max', 'mini', 'pro', 'ultra', 'elite', 'evo', 'se', 'lite',
 'liquid', 'soc']
KEY_AIB = frozenset(['dual', 'tuf', 'prime', 'rog', 'strix', 'proart', 'ventus', 'eagle', 'aorus', 'windforce', 'pulse', 'nitro',
 'hellhound', 'fighter', 'challenger', 'steellegend', 'taichi', 'phantom', 'suprim', 'gamerock', 'trio',
 'ironclad', 'igame', 'battleax', 'twin', 'ghost', 'hawk', 'mech', 'gungnir', 'tomahawk', 'carbon', 'riptide',
 'swift', 'solidcore', 'inspire', 'vision', 'solid', 'trinity', 'amp', 'airo', 'spectra', 'aero', 'xtreme',
 'waterforce', 'infinity'])
MB_CHIPSETS = {'X870E': ['AM5', 'DDR5', 'high'],
 'X870': ['AM5', 'DDR5', 'high'],
 'B850': ['AM5', 'DDR5', 'mid'],
 'B840': ['AM5', 'DDR5', 'entry'],
 'X670E': ['AM5', 'DDR5', 'high'],
 'X670': ['AM5', 'DDR5', 'high'],
 'B650E': ['AM5', 'DDR5', 'mid'],
 'B650': ['AM5', 'DDR5', 'mid'],
 'A620': ['AM5', 'DDR5', 'entry'],
 'X570': ['AM4', 'DDR4', 'high'],
 'B550': ['AM4', 'DDR4', 'mid'],
 'B450': ['AM4', 'DDR4', 'mid'],
 'X470': ['AM4', 'DDR4', 'mid'],
 'A520': ['AM4', 'DDR4', 'entry'],
 'B350': ['AM4', 'DDR4', 'mid'],
 'A320': ['AM4', 'DDR4', 'entry'],
 'WRX90': ['sTR5', 'DDR5', 'high'],
 'TRX50': ['sTR5', 'DDR5', 'high'],
 'WRX80': ['sWRX8', 'DDR4', 'high'],
 'TRX40': ['sTRX4', 'DDR4', 'high'],
 'Z890': ['LGA1851', 'DDR5', 'high'],
 'B860': ['LGA1851', 'DDR5', 'mid'],
 'H810': ['LGA1851', 'DDR5', 'entry'],
 'W880': ['LGA1851', 'DDR5', 'high'],
 'Z790': ['LGA1700', 'DDR5', 'high'],
 'Z690': ['LGA1700', 'DDR5', 'high'],
 'B760': ['LGA1700', 'DDR5', 'mid'],
 'B660': ['LGA1700', 'DDR5', 'mid'],
 'H770': ['LGA1700', 'DDR5', 'mid'],
 'H670': ['LGA1700', 'DDR5', 'mid'],
 'H610': ['LGA1700', 'DDR4', 'entry'],
 'Z590': ['LGA1200', 'DDR4', 'high'],
 'Z490': ['LGA1200', 'DDR4', 'high'],
 'B560': ['LGA1200', 'DDR4', 'mid'],
 'H570': ['LGA1200', 'DDR4', 'mid'],
 'H510': ['LGA1200', 'DDR4', 'entry'],
 'H470': ['LGA1200', 'DDR4', 'mid'],
 'B460': ['LGA1200', 'DDR4', 'mid'],
 'Z390': ['LGA1151', 'DDR4', 'high'],
 'Z370': ['LGA1151', 'DDR4', 'high'],
 'B365': ['LGA1151', 'DDR4', 'mid'],
 'B360': ['LGA1151', 'DDR4', 'mid'],
 'H370': ['LGA1151', 'DDR4', 'mid'],
 'H310': ['LGA1151', 'DDR4', 'entry']}
M2_BY_TIER = {'high': 4, 'mid': 3, 'entry': 2}
JUNK_TITLE = re.compile(r"""^(sponsored$|bestseller$|trending$|sold out|coming soon|flipkart's choice|currently unavailable|deal of the|limited time|great indian|see (more|all|options)|shop now|check each|results?$|next$|previous$|page \d+$|\+\d+ other|debug info|^\u20b9[\d,.]+.{0,16}% ?off$|get it (faster|by|as)|free delivery|save extra|with exchange|only \d+ left|\d+ bought|[\d.,\s]+$)""", re.ASCII | re.I)
NON_PC = re.compile(r"""shapewear|innerwear|underwear|\bbriefs?\b|\bsaree\b|\bkurta\b|t-?shirt|\bjeans\b|footwear|\bsandal|slipper|sneaker|perfume|deodorant|shampoo|lipstick|makeup|face ?wash|\bvitamin|protein (powder|bar)|supplement|sculpture|relief art|craft kit|\bdiaper|cookware|mixer grinder|air fryer|vacuum cleaner|water bottle|bedsheet|\bpillow\b|curtain|umbrella|sunglass|funny quote|wall art|photo frame|home decor|jewell?ery|bracelet|necklace|\bdslr\b|mirrorless|\baps-c\b|camera lens|lens (hood|filter)|\bkennel\b|chicken chunks|in gravy|dog food|cat food|pet food|cold weld|mending epoxy|mediatek dimensity|mediatek helio|carplay|android auto|dash ?cam|smart tv|google tv|\btelevision\b|android tv|\bfujifilm\b|view ?finder|\bvalentine\b|\bipad\b|whiteboard|interactive (smart )?display|smartvue|dji osmo|action camera|\bgopro\b|oura ring|sizing kit|stickers? for (home|wall)|vr (box|headset).{0,60}(mobile|phone|android|iphone)|\bled tv\b|for led tv|tv (motherboard|mainboard)""", re.ASCII | re.I)
GAME_TITLES = re.compile(r"""\b(fifa|efootball|uncharted|god of war|spider-?man|grand theft|elden ring|hogwarts|assassin'?s creed|mortal kombat|tekken|gran turismo|forza|zelda|mario|yakuza|final fantasy|resident evil|silent hill|cyberpunk|witcher|horizon (forbidden|zero)|ghost of|last of us|dark souls|sekiro|street fighter|nba 2k\d+|wwe 2k\d+|f1 2\d|ufc \d|cricket 2\d|skull (&|and) bones|far cry|watch dogs|dying light|diablo|starfield|baldur'?s gate|red dead|the crew|need for speed|it takes two|little nightmares|stellar blade|helldivers|returnal|ratchet|sackboy|demon'?s souls|bloodborne|death stranding|days gone|detroit become|nier|persona \d|monster hunter|kingdom hearts|crash bandicoot|prince of persia|star wars (outlaws|jedi)|hitman|tomb raider|just dance|black myth|wukong|split fiction|call of duty|dragon ball|naruto|one piece|onimusha|ghost recon|rainbow six|dead island|lords of the fallen|lies of p|ea sports fc|\bfc\s?2[4-6]\b|switch sports?|mario kart|smash bros|splatoon|pikmin|kirby|metroid|donkey kong|animal crossing|pok[e\u00e9]mon|marvel'?s avengers|\bavengers\b)\b""", re.ASCII)
JUNK = re.compile(r"""test\s*product|placeholder|dummy|click to learn|this sponsored product|view details|add to cart""", re.ASCII | re.I)
